void do_exception(void);
